# Generated by Django 3.1.6 on 2021-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradespeople', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradespeople',
            options={'verbose_name_plural': 'Trades People'},
        ),
        migrations.AddField(
            model_name='tradespeople',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='tradespeople',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
