# Generated by Django 3.1.6 on 2021-02-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20210225_1155'),
        ('tradespeople', '0002_auto_20210223_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trades_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradespeople.tradespeople')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
            ],
        ),
    ]
