# Generated by Django 3.1.6 on 2021-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimmable',
            field=models.BooleanField(default=False),
        ),
    ]
